"""
Prometheus metrics for the GATE Trading Intelligence Platform.
Import and call setup_metrics(app) in main.py after app creation.
"""
from prometheus_client import Counter, Histogram, Gauge
from prometheus_fastapi_instrumentator import Instrumentator

# --- Scan metrics ---
scan_duration = Histogram(
    "gate_scan_duration_seconds",
    "End-to-end GATE scan pipeline duration",
    buckets=[5, 10, 30, 60, 120, 300, 600],
)

signals_found = Counter(
    "gate_signals_found_total",
    "Total signals generated by the GATE scanner",
    labelnames=["category"],
)

scan_errors = Counter(
    "gate_scan_errors_total",
    "Total GATE scan failures",
    labelnames=["error_type"],
)

# --- Market data metrics ---
yfinance_errors = Counter(
    "gate_yfinance_errors_total",
    "yfinance fetch errors",
    labelnames=["symbol", "interval"],
)

cache_hits = Counter(
    "gate_parquet_cache_hits_total",
    "Parquet disk-cache hits",
    labelnames=["interval"],
)

cache_misses = Counter(
    "gate_parquet_cache_misses_total",
    "Parquet disk-cache misses",
    labelnames=["interval"],
)

# --- Redis price cache ---
price_cache_hits = Counter(
    "gate_redis_price_cache_hits_total",
    "Redis price-cache hits",
)

price_cache_misses = Counter(
    "gate_redis_price_cache_misses_total",
    "Redis price-cache misses",
)

# --- WebSocket ---
ws_connections = Gauge(
    "gate_ws_connections_active",
    "Active WebSocket connections",
)

# --- Celery task metrics ---
celery_tasks_total = Counter(
    "gate_celery_tasks_total",
    "Celery tasks dispatched",
    labelnames=["task_name", "status"],
)


def setup_metrics(app):
    """Wire Prometheus instrumentation onto the FastAPI app."""
    Instrumentator(
        should_group_status_codes=True,
        should_ignore_untemplated=True,
        excluded_handlers=["/api/health", "/metrics"],
    ).instrument(app).expose(app, endpoint="/metrics", include_in_schema=False)
